parameters:
    pad.default.generate:
        default:
            default:
                classes:
                    - 'block_full_slider'
                    - 'block_full_parallax'
                    - 'block_parallax_slider'
                    - 'block_youtube'
                    - 'block_text'
                    - 'block_image'
                limit: 10
                template: 'PadMayaBundle::foreach.html.twig'
                viewType: 'item'
        container:
            block_full_slider:
                classes: ['image']
                viewType: slide
                template: 'PadMayaBundle::foreach.html.twig'
                limit: 10
            block_parallax_slider:
                classes: ['image']
                template: 'PadMayaBundle::foreach.html.twig'
                viewType: item
                limit: 10
            block_list_page:
                classes: ['page']
                template: 'PadMayaBundle::foreach.html.twig'
                viewType: item
                limit: 10
        page:
            full:
                classes:
                    - 'block_full_slider'
                    - 'block_full_parallax'
                    - 'block_parallax_slider'
                    - 'block_youtube'
                    - 'block_text'
                    - 'block_list_page'
                    - 'block_contact'
                limit: 10
                template: 'PadMayaBundle:foreach:page.html.twig'
                viewType: 'container'
